src/components/sections/Testimony/Card.tsx
src/pages/communs/index.tsx
src/styles/globals.css

Here are a few things either required or really adviced for better UX for everyone.
Screenshots showing before/after for each commit:
https://github.com/numerique-gouv/lasuite-landingpage/commit/b08b4955b858d8f291d6ce3ccbef0b4dfa44b989
https://github.com/numerique-gouv/lasuite-landingpage/commit/b4cd8938da7c5bfaad64b24d70377e523222cc5e
https://github.com/numerique-gouv/lasuite-landingpage/commit/5cff15f380ee66074d7a59ca3c146ad63c9fd80e
pouet @lebaudantoine

Design changes proposal for better accessibility

---

src/components/Layout/ContentPage.tsx

🐛(tsc) fix unexisting import that I forgot to delete

---

public/robots.txt
public/sitemap.xml
robots.txt
sitemap.xml
src/components/Layout/MetaHeader.tsx

⚠️ This PR is draft because I wait for Joel to give me the Google verification code ⚠️
But @manuhabitela you can already review the code.
Prepare bare minimum SEO tools for the marketing team

Enhance marketing configurations

---

src/components/sections/ANCT/index.tsx
src/components/sections/CallForProjects/Section.tsx
src/components/sections/DigitalCommons/Section.tsx

Based on Camille and Sabine feedbacks, fix minor typos.

✏️(content) fix some minor typos

---

src/components/Footer.tsx
src/styles/app.css
tailwind.config.ts

Align the website with the official logo
Quick and dirty approach to align footer with recent design changes.

Update footer's logo

---

src/components/Footer.tsx
src/sections/DigitalCommons.tsx
src/sections/Hero.tsx
src/sections/Testimonies.tsx

We received feedback from stakeholders.
Fix content typos and redundancies.

🚸(content) fix typos and improve content

---

package.json
src/components/Br.tsx
src/components/Button.tsx
src/components/ContentSection.tsx
src/components/ExternalLink.tsx
src/components/Footer.tsx
src/components/Layout.tsx
src/components/NavBar.tsx
src/pages/404.tsx
src/pages/communs.tsx
src/pages/index.tsx
src/sections/Anct.tsx
src/sections/DigitalCommons.tsx
src/sections/Initiatives.tsx
src/sections/ProConnect.tsx
src/sections/Testimonies.tsx
src/types.ts
tailwind.config.ts
yarn.lock

Improve DX and code maintainability 
Based on peer feedback, and good practice. Try to encapsulate styling for core components.

Improve style encapsulation

---

package.json
src/components/LaGaufre.tsx
src/components/NavBar.tsx
yarn.lock

including the gaufre button that is an external
tool to list all suite related apps
_this is just a test to publish a review app_
edit: updated with production-ready code.

✨(header) add Gaufre button

---

src/cms/config.prod.ts

this is meant to prevent needing content authors to have admin rights to bypass branch protection rules
creating a PR mostly to create review app to try it out

✨(cms) enable editorial workflow

---

src/components/HomepageContent.tsx

We just saw this one quite lately, but here is a fix.

✏️(front) fix typo on the main page

---

content/service-pages/fr/grist.yml

incubateur.net is depreciated
also adds a link to the forum

update grist service page

---

.github/PULL_REQUEST_TEMPLATE.md
.gitignore
CONTRIBUTING.md
README.md
package.json
tools/install_gitlint.sh
tools/requirements-gitlint.txt
tools/run_gitlint.sh

Help developers to comply with the commit rules and provide help for their first contributions.
- Create a contribution guide
- Add scripts to use gitlint
- Add comments to the PR template to suggest using the lint scripts

Contribution guidance

---

content/service-pages/fr/grist.yml

🔧(landing-pages) change grist video

---

package-lock.json
src/locales/en.yml
src/locales/fr.yml
yarn.lock

Cette PR modifie certains textes de l’interface pour refléter plus fidèlement la vision portée par la DINUM. 
La Suite n’est pas un produit fermé ou exclusif, mais un ensemble de communs numériques réutilisables, conçus pour le secteur public, au service de la souveraineté, de la simplicité et de l’efficacité de l’État.
🎯 Objectif
Éviter les incompréhensions ou critiques sur un positionnement perçu comme monopolistique (« l’espace de travail souverain »), et affirmer que La Suite s’inscrit dans une logique de communs ouverts, disponibles pour les ministères, les collectivités, mais aussi pour les éditeurs partenaires.
✅ Résultat attendu
Un discours plus clair et inclusif, cohérent avec notre stratégie de mutualisation, d’ouverture du code et d’interopérabilité.
Cela permettra aussi aux …

Clarification du positionnement de La Suite Numérique : mise en avant des communs numériques

---

src/locales/en.yml

✨(front) add section communs

---

src/components/NavBar.tsx
src/sections/Homepage/Communs.tsx
src/utils/products.tsx

✨(front) change tchap url + fix style

---

content/content-pages/fr/services-en-beta.yml

This should let us remove the beta logo on a couple of our products.

✨(front) publish beta page

---

content/content-pages/fr/services-en-beta.yml

Some comments were left in the text
Sorry 🫡

✨(front) fix wording for beta page

---

content/service-pages/fr/grist.yml
src/locales/fr.yml
src/utils/products.tsx

with matomo tracking + make sure it links to signup

💬(grist) update grist links

---

src/utils/products.tsx

let the landing page + redirect magic do their work
We want people clicking on the homepage link to go to the landing page if they are not logged in.

💬(grist) update grist link on homepage
